### PR TITLE
Discrete Math: update PNF lecture notes shots

### PR DESCRIPTION
**Pull request by Amr-Hash**
I updated discrete mathematics lecture slides shots about PNF equations by the value in the PDF file which is different than the one represented in the shots.

### CODE REVIEW

**Comment by DrWaleedAYousef** [comment]
Thanks so much for your concern; however, I did not see the difference between the 3 original files and the modified. They are exactly the same!

**Comment by Amr-Hash** [comment]
It's exactly in that part in the file 
Teaching/DiscreteMathematics/LectureNotes/Shots/2016-03-23--16.13.46.png
image

as it suppose to be like that
image

and the same for other two files 
DiscreteMathematics/LectureNotes/Shots/2016-03-23--16.18.20.png
and
DiscreteMathematics/LectureNotes/Shots/2016-03-23--16.21.00.png

**Comment by DrWaleedAYousef** [comment]
Oh, I see now. I was looking at the red and blue handwriting as I did not think that the typos are in the main text, since it is just a snapshot from the PDF. What probably happend is that I took the snapshot, then found the typo and corrected it in the PDF. Thanks.

**Comment by Amr-Hash** [comment]
جزاك الله خيرا يا دكتور .. نفع الله بنا وبكم

**Pull request merged**
